// Code generated by "stringer -type githubEventType github_event_type.go"; DO NOT EDIT

package models

import (
	"fmt"
)

const _githubEventType_name = "CommitCommentEventCreateEventDeleteEventDeploymentEventDeploymentStatusEventDownloadEventFollowEventForkEventForkApplyEventGistEventGollumEventIssueCommentEventIssuesEventLabelEventMemberEventMembershipEventMilestoneEventOrganizationEventOrgBlockEventPageBuildEventProjectCardEventProjectColumnEventProjectEventPublicEventPullRequestEventPullRequestReviewEventPullRequestReviewCommentEventPushEventReleaseEventRepositoryEventStatusEventTeamEventTeamAddEventWatchEvent"

var _githubEventType_index = [...]uint16{0, 18, 29, 40, 55, 76, 89, 100, 109, 123, 132, 143, 160, 171, 181, 192, 207, 221, 238, 251, 265, 281, 299, 311, 322, 338, 360, 389, 398, 410, 425, 436, 445, 457, 467}

func (i githubEventType) String() string {
	if i < 0 || i >= githubEventType(len(_githubEventType_index)-1) {
		return fmt.Sprintf("githubEventType(%d)", i)
	}
	return _githubEventType_name[_githubEventType_index[i]:_githubEventType_index[i+1]]
}
